src/DQL_trainer.py:209: UserWarning: Using a target size (torch.Size([256, 256])) that is different to the input size (torch.Size([256])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  loss = nn.functional.mse_loss(current_q_values, target_q_values, reduction='sum')
name: AdaptiveSampling
device: cpu
num_trials: 5
num_episodes: 44
replay_batch_size: 256
epsilon_decay_rate: 1
max_epsilon: 1.0
min_epsilon: 0.01
learning_rate_min: 1e-05
learning_rate_max: 0.003
gamma: 0.99
target_network_update_rate: 1000
tau: 0.1
replay_memory_size: 1000000
Trial 1
subject_num: 0
environment.num_data_segments_train: 2271
subject_num: 1
environment.num_data_segments_train: 1862
subject_num: 2
environment.num_data_segments_train: 2083
subject_num: 3
environment.num_data_segments_train: 2567
subject_num: 4
environment.num_data_segments_train: 2027
subject_num: 5
environment.num_data_segments_train: 1760
subject_num: 6
environment.num_data_segments_train: 2529
subject_num: 7
environment.num_data_segments_train: 2124
subject_num: 8
environment.num_data_segments_train: 2538
subject_num: 9
environment.num_data_segments_train: 1794
subject_num: 10
environment.num_data_segments_train: 1875
subject_num: 11
environment.num_data_segments_train: 1952
subject_num: 12
environment.num_data_segments_train: 2411
subject_num: 13
environment.num_data_segments_train: 1534
subject_num: 14
environment.num_data_segments_train: 2277
subject_num: 15
environment.num_data_segments_train: 1987
subject_num: 16
environment.num_data_segments_train: 1862
subject_num: 17
environment.num_data_segments_train: 2474
subject_num: 18
environment.num_data_segments_train: 1517
subject_num: 19
environment.num_data_segments_train: 1613
subject_num: 20
environment.num_data_segments_train: 433
subject_num: 21
environment.num_data_segments_train: 442
subject_num: 22
environment.num_data_segments_train: 265
subject_num: 23
environment.num_data_segments_train: 498
subject_num: 24
environment.num_data_segments_train: 455
subject_num: 25
environment.num_data_segments_train: 267
subject_num: 26
environment.num_data_segments_train: 446
subject_num: 27
environment.num_data_segments_train: 486
subject_num: 28
environment.num_data_segments_train: 444
subject_num: 29
environment.num_data_segments_train: 463
subject_num: 30
environment.num_data_segments_train: 457
subject_num: 31
environment.num_data_segments_train: 382
subject_num: 32
environment.num_data_segments_train: 568
subject_num: 33
environment.num_data_segments_train: 380
subject_num: 34
environment.num_data_segments_train: 353
subject_num: 35
environment.num_data_segments_train: 407
subject_num: 36
environment.num_data_segments_train: 366
subject_num: 37
environment.num_data_segments_train: 400
subject_num: 38
environment.num_data_segments_train: 350
subject_num: 39
environment.num_data_segments_train: 396
subject_num: 40
environment.num_data_segments_train: 293
subject_num: 41
environment.num_data_segments_train: 295
subject_num: 42
environment.num_data_segments_train: 512
subject_num: 43
environment.num_data_segments_train: 462
epsilon: 0.802
Trial 2
Traceback (most recent call last):
  File "src/DQL_trainer.py", line 133, in <module>
  File "/dfs6/pub/panwangc/custom_DRL/JBHI_2022/src/Environment.py", line 37, in __init__
  File "/dfs6/pub/panwangc/custom_DRL/JBHI_2022/src/Environment.py", line 72, in load_data
FileNotFoundError: [Errno 2] No such file or directory: '/pub/panwangc/custom_DRL/JBHI_2022/to_Luke.pickle'
